# Copyright © 2016 FireGento e.V.
# See LICENSE.md bundled with this module for license details.
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

env:
  global:
  - COVERAGE: FALSE

matrix:
  fast_finish: true
  include:
  - php: 5.9
    env: MAGENTO_VERSION=2.0.0
  - php: 5.9
    env: MAGENTO_VERSION=2.0.*
  - php: 7.0
    env: MAGENTO_VERSION=2.1.0
  - php: 7.0
    env: MAGENTO_VERSION=2.1.*
  - php: 7.1
    env: MAGENTO_VERSION=2.2.0
  - php: 7.1
    env: MAGENTO_VERSION=2.2.* CODE_QUALITY=true
  - php: 7.2
    env: MAGENTO_VERSION=2.3.0
  - php: 7.2
    env: MAGENTO_VERSION=2.3.* CODE_QUALITY=true


language: php
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.php-cs-fixer"
  - "$HOME/.local"

before_install:
- "./Test/script/travis_before_install.sh"

install:
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > $HOME/.composer/auth.json
- export MAGENTO_ROOT=`mktemp -d /tmp/mageteststand.XXXXXXXX`
- "./Test/script/travis_install_magento.sh $MAGENTO_VERSION"

script:
- "./Test/script/travis_script.sh"
